### PR TITLE
Add beta branch configuration

### PR DESCRIPTION
**Pull request by jechague**
Issue:89953

### CODE REVIEW

**Review by sjuarezgx — DISMISSED** [review]

**Review by anaiberta — CHANGES_REQUESTED** [review]
'master' and 'beta' branches must use a pre-release version to avoid confusion about 'release-*' and 'master' versions.

**Comment by jechague** [comment]
> 'master' and 'beta' branches must use a pre-release version to avoid confusion about 'release-*' and 'master' versions.
> 
> We cannot use pre-releases version with GPR :S, so we will need to configure GitHub-Builder for this repo and move the calculation of the version to another file.

Then we need to stop using a nuspec in favor of a SLN to create the NuGet packages as GitHub-Builder only accepts the latter. @sjuarezgx could you do that in a separate PR?

**Comment by jechague** [comment]
> > 'master' and 'beta' branches must use a pre-release version to avoid confusion about 'release-*' and 'master' versions.
> > We cannot use pre-releases version with GPR :S, so we will need to configure GitHub-Builder for this repo and move the calculation of the version to another file.
> 
> Then we need to stop using a nuspec in favor of a SLN to create the NuGet packages as GitHub-Builder only accepts the latter. @sjuarezgx could you do that in a separate PR?

PR. #10 created the required VS SLN. I've pushed the necessary changes to this branch to dispatch builds from the master and beta branches to our internal builders.

**Review by anaiberta — APPROVED** [review]
LGTM

**Pull request merged**
